[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.build]
cmds = [
  "npm --prefix controller-web install",
  "npm --prefix controller-web run build",
  "npm --prefix server install",
  "npm install"
]

[start]
cmd = "node server/index.js"
