services:
  - type: web
    name: remoteg-all-in-one
    runtime: node
    plan: free
    buildCommand: cd controller-web && npm install && npm run build && cd ../server && npm install
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

