services:
  - type: web
    name: remote-desktop-signaling
    runtime: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 5000
