services:
  - type: web
    name: remote-desktop-signaling
    runtime: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 5000

  - type: static
    name: remoteg-portal
    rootDir: controller-web
    buildCommand: npm install && npm run build
    publishPath: dist
